// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "VVDSupport",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "VVDSupport",
            type: .static,
            targets: [
                "VVDHelper",
                "_zlib",
                ]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "VVDHelper",
            dependencies: [
                "_libpng",
                "_jpeg",
                "_zlib",
                "_lz4",
                "_lzma",
                "_zstd",
                "_libogg",
                "_libvorbis",
                "_libFLAC",
                ],
            path: "Sources/VVDHelper",
            publicHeadersPath: ".",
            cSettings: [],
            cxxSettings: [
                .headerSearchPath("../libogg/include"),
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH", .when(platforms:[.windows])),
                .unsafeFlags([
                    "-Wno-module-import-in-extern-c",
                ])
            ],
            linkerSettings: []),
        .target(
            name: "_jpeg",
            path: "Sources/jpeg",
            sources: [
                "jaricom.c",
                "jcapimin.c",
                "jcapistd.c",
                "jcarith.c",
                "jccoefct.c",
                "jccolor.c",
                "jcdctmgr.c",
                "jchuff.c",
                "jcinit.c",
                "jcmainct.c",
                "jcmarker.c",
                "jcmaster.c",
                "jcomapi.c",
                "jcparam.c",
                "jcprepct.c",
                "jcsample.c",
                "jctrans.c",
                "jdapimin.c",
                "jdapistd.c",
                "jdarith.c",
                "jdatadst.c",
                "jdatasrc.c",
                "jdcoefct.c",
                "jdcolor.c",
                "jddctmgr.c",
                "jdhuff.c",
                "jdinput.c",
                "jdmainct.c",
                "jdmarker.c",
                "jdmaster.c",
                "jdmerge.c",
                "jdpostct.c",
                "jdsample.c",
                "jdtrans.c",
                "jerror.c",
                "jfdctflt.c",
                "jfdctfst.c",
                "jfdctint.c",
                "jidctflt.c",
                "jidctfst.c",
                "jidctint.c",
                "jmemmgr.c",
                "jmemnobs.c",
                "jquant1.c",
                "jquant2.c",
                "jutils.c",
            ],
            publicHeadersPath: ".",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
            ]),
        .target(
            name: "_libpng",
            dependencies: [.target(name: "_zlib")],
            path: "Sources/libpng",
            sources: [
                "png.c",
                "pngerror.c",
                "pngget.c",
                "pngmem.c",
                "pngpread.c",
                "pngread.c",
                "pngrio.c",
                "pngrtran.c",
                "pngrutil.c",
                "pngset.c",
                "pngtrans.c",
                "pngwio.c",
                "pngwrite.c",
                "pngwtran.c",
                "pngwutil.c",
                "arm/arm_init.c",
                "arm/filter_neon_intrinsics.c",
            ],
            publicHeadersPath: ".",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                //.define("PNG_INTEL_SSE", .when(platforms: [.windows])),
                .unsafeFlags([
                    "-Wno-tautological-constant-out-of-range-compare",
                    "-Wno-incompatible-pointer-types-discards-qualifiers"
                ])
            ]),
        .target(
            name: "_libogg",
            path: "Sources/libogg",
            sources : ["src"],
            publicHeadersPath: "include"),
        .target(
            name: "_libvorbis",
            dependencies: [.target(name: "_libogg")],
            path: "Sources/libvorbis",
            sources: [
                "src/analysis.c",
                "src/bitrate.c",
                "src/block.c",
                "src/codebook.c",
                "src/envelope.c",
                "src/floor0.c",
                "src/floor1.c",
                "src/info.c",
                "src/lookup.c",
                "src/lpc.c",
                "src/lsp.c",
                "src/mapping0.c",
                "src/mdct.c",
                "src/psy.c",
                "src/registry.c",
                "src/res0.c",
                "src/sharedbook.c",
                "src/smallft.c",
                "src/synthesis.c",
                "src/vorbisenc.c",
                "src/vorbisfile.c",
                "src/window.c"],
            publicHeadersPath: "include",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("HAVE_CONFIG_H"),
            ]),
        .target(
            name: "_libFLAC",
            dependencies: [.target(name: "_libogg")],
            path: "Sources/libFLAC",
            sources: ["src/libFLAC"],
            publicHeadersPath: ".",
            cSettings: [
                .define("fseeko", to: "fseek", .when(platforms: [.windows, .android])),    
                .define("ftello", to: "ftell", .when(platforms: [.windows, .android])),
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_CRT_NONSTDC_NO_WARNINGS", .when(platforms: [.windows])),
                .headerSearchPath("include"),
                .unsafeFlags([
                    "-Wno-enum-conversion",
                    "-Wno-int-conversion",
                    "-Wno-tautological-constant-out-of-range-compare",
                    "-Wno-sizeof-pointer-memaccess",
                    "-Wno-implicit-function-declaration",
                ])
            ]),
        .target(
            name: "_lz4",
            path: "Sources/lz4",
            sources: [
                "lib/lz4.c",
                "lib/lz4frame.c",
                "lib/lz4hc.c",
                "lib/xxhash.c"],
            publicHeadersPath: "."),
        .target(
            name: "_lzma",
            path: "Sources/lzma",
            exclude: [],
            sources: [
                "C/7zAlloc.h",
                "C/7zArcIn.c",
                "C/7zBuf.c",
                "C/7zBuf2.c",
                "C/7zCrc.c",
                "C/7zCrcOpt.c",
                "C/7zDec.c",
                "C/7zFile.c",
                "C/7zStream.c",
                "C/Aes.c",
                "C/AesOpt.c",
                "C/Alloc.c",
                "C/Bcj2.c",
                "C/Bcj2Enc.c",
                "C/Bra.c",
                "C/Bra86.c",
                "C/BraIA64.c",
                "C/CpuArch.c",
                "C/Delta.c",
                "C/LzFind.c",
                "C/Lzma2Dec.c",
                "C/Lzma2DecMt.c",
                "C/Lzma2Enc.c",
                "C/Lzma86Dec.c",
                "C/Lzma86Enc.c",
                "C/LzmaDec.c",
                "C/LzmaEnc.c",
                "C/LzmaLib.c",
                "C/Ppmd7.c",
                "C/Ppmd7Dec.c",
                "C/Ppmd7Enc.c",
                "C/Sha256.c",
                "C/Sort.c",
                "C/Xz.c",
                "C/XzCrc64.c",
                "C/XzCrc64Opt.c",
                "C/XzDec.c",
                "C/XzEnc.c",
                "C/XzIn.c"
                ],
            publicHeadersPath: ".",
            cSettings: [
                .define("_7ZIP_ST"),
                //.unsafeFlags(["-march=native"]),
            ]),
        .target(
            name: "_zlib",
            path: "Sources/zlib",
            sources: [
                "adler32.c",
                "compress.c",
                "crc32.c",
                "deflate.c",
                "gzclose.c",
                "gzlib.c",
                "gzread.c",
                "gzwrite.c",
                "infback.c",
                "inffast.c",
                "inflate.c",
                "inftrees.c",
                "trees.c",
                "uncompr.c",
                "zutil.c"],
            publicHeadersPath: ".",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_CRT_NONSTDC_NO_WARNINGS", .when(platforms: [.windows])),
                .unsafeFlags([
                    "-Wno-shift-negative-value",
                    "-Wno-deprecated-non-prototype",
                ])
            ]),
        .target(
            name: "_zstd",
            path: "Sources/zstd",
            exclude: ["lib/common/xxhash.c"], // duplicated, use lz4 instead
            sources: [
                "lib/common",
                "lib/compress",
                "lib/decompress",
                "lib/dictBuilder",
            ],
            publicHeadersPath: ".",
            cSettings: [
                .headerSearchPath("lib"),
                .headerSearchPath("lib/common"),
                .headerSearchPath("lib/dictBuilder")]
        ),
    ],
    cLanguageStandard: .c17,
    cxxLanguageStandard: .cxx17
)
