// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "DKGame-ThirdParty",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "DKGame-ThirdParty",
            targets: [
                "DKGameSupport",
                "DKGameUtils",
                "SPIRV_Cross",
                "FreeType",
                "jpeg",
                "libpng",
                "libogg",
                "libvorbis",
                "libFLAC",
                "lz4",
                "lzma",
                "zlib",
                "zstd",
                ]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "DKGameSupport",
            dependencies: []),
        .target(
            name: "DKGameUtils",
            dependencies: ["libpng", "jpeg", "zlib", "lz4", "lzma", "zstd", "libvorbis", "libFLAC"],
            path: "Sources/DKGameUtils",
            publicHeadersPath: "."
            ),
        .target(
            name: "SPIRV_Cross",
            path: "Sources/SPIRV-Cross",
            sources: [
                "spirv_cfg.cpp",
                "spirv_cpp.cpp",
                "spirv_cross.cpp",
                "spirv_cross_c.cpp",
                "spirv_cross_parsed_ir.cpp",
                "spirv_cross_util.cpp",
                "spirv_glsl.cpp",
                "spirv_hlsl.cpp",
                "spirv_msl.cpp",
                "spirv_parser.cpp",
                "spirv_reflect.cpp"],
            publicHeadersPath: "swift_public_headers"),
        .target(
            name: "FreeType",
            dependencies: [.target(name: "zlib")],
            path: "Sources/FreeType",
            sources: [
                "src/autofit/autofit.c",
                "src/base/ftbase.c",
                "src/base/ftbbox.c",
                "src/base/ftbdf.c",
                "src/base/ftbitmap.c",
                "src/base/ftcid.c",
                "src/base/ftdebug.c",
                "src/base/ftfntfmt.c",
                "src/base/ftfstype.c",
                "src/base/ftgasp.c",
                "src/base/ftglyph.c",
                "src/base/ftgxval.c",
                "src/base/ftinit.c",
                "src/base/ftlcdfil.c",
                "src/base/ftmm.c",
                "src/base/ftotval.c",
                "src/base/ftpatent.c",
                "src/base/ftpfr.c",
                "src/base/ftstroke.c",
                "src/base/ftsynth.c",
                "src/base/ftsystem.c",
                "src/base/fttype1.c",
                "src/base/ftwinfnt.c",
                "src/bdf/bdf.c",
                "src/cache/ftcache.c",
                "src/cff/cff.c",
                "src/cid/type1cid.c",
                "src/gzip/ftgzip.c",
                "src/lzw/ftlzw.c",
                "src/pcf/pcf.c",
                "src/pfr/pfr.c",
                "src/psaux/psaux.c",
                "src/pshinter/pshinter.c",
                "src/psnames/psmodule.c",
                "src/raster/raster.c",
                "src/sfnt/sfnt.c",
                "src/smooth/smooth.c",
                "src/truetype/truetype.c",
                "src/type1/type1.c",
                "src/type42/type42.c",
                "src/winfonts/winfnt.c"],
            publicHeadersPath: "include",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms:[.windows])),
                .define("FT2_BUILD_LIBRARY"),
                .define("FT_DEBUG_LEVEL_ERROR", .when(configuration:.debug)),
                .define("FT_DEBUG_LEVEL_TRACE", .when(configuration:.debug)),
                .headerSearchPath("include"),
                .unsafeFlags([
                    "-Wno-format"
                ]),
            ]),
        .target(
            name: "jpeg",
            path: "Sources/jpeg",
            sources: [
                "jaricom.c",
                "jcapimin.c",
                "jcapistd.c",
                "jcarith.c",
                "jccoefct.c",
                "jccolor.c",
                "jcdctmgr.c",
                "jchuff.c",
                "jcinit.c",
                "jcmainct.c",
                "jcmarker.c",
                "jcmaster.c",
                "jcomapi.c",
                "jcparam.c",
                "jcprepct.c",
                "jcsample.c",
                "jctrans.c",
                "jdapimin.c",
                "jdapistd.c",
                "jdarith.c",
                "jdatadst.c",
                "jdatasrc.c",
                "jdcoefct.c",
                "jdcolor.c",
                "jddctmgr.c",
                "jdhuff.c",
                "jdinput.c",
                "jdmainct.c",
                "jdmarker.c",
                "jdmaster.c",
                "jdmerge.c",
                "jdpostct.c",
                "jdsample.c",
                "jdtrans.c",
                "jerror.c",
                "jfdctflt.c",
                "jfdctfst.c",
                "jfdctint.c",
                "jidctflt.c",
                "jidctfst.c",
                "jidctint.c",
                "jmemmgr.c",
                "jmemnobs.c",
                "jquant1.c",
                "jquant2.c",
                "jutils.c",
            ],
            publicHeadersPath: ".",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
            ]),
        .target(
            name: "libpng",
            dependencies: [.target(name: "zlib")],
            path: "Sources/libpng",
            sources: [
                "png.c",
                "pngerror.c",
                "pngget.c",
                "pngmem.c",
                "pngpread.c",
                "pngread.c",
                "pngrio.c",
                "pngrtran.c",
                "pngrutil.c",
                "pngset.c",
                "pngtrans.c",
                "pngwio.c",
                "pngwrite.c",
                "pngwtran.c",
                "pngwutil.c"
            ],
            publicHeadersPath: "include",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                //.define("PNG_INTEL_SSE", .when(platforms: [.windows])),
                .unsafeFlags([
                    "-Wno-tautological-constant-out-of-range-compare",
                ])
            ]),
        .target(
            name: "libogg",
            path: "Sources/libogg",
            sources : ["src"],
            publicHeadersPath: "include"),
        .target(
            name: "libvorbis",
            dependencies: [.target(name: "libogg")],
            path: "Sources/libvorbis",
            sources: [
                "src/analysis.c",
                "src/bitrate.c",
                "src/block.c",
                "src/codebook.c",
                "src/envelope.c",
                "src/floor0.c",
                "src/floor1.c",
                "src/info.c",
                "src/lookup.c",
                "src/lpc.c",
                "src/lsp.c",
                "src/mapping0.c",
                "src/mdct.c",
                "src/psy.c",
                "src/registry.c",
                "src/res0.c",
                "src/sharedbook.c",
                "src/smallft.c",
                "src/synthesis.c",
                "src/vorbisenc.c",
                "src/vorbisfile.c",
                "src/window.c"],
            publicHeadersPath: "include",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
            ]),
        .target(
            name: "libFLAC",
            dependencies: [.target(name: "libogg")],
            path: "Sources/libFLAC",
            sources: ["src/libFLAC"],
            publicHeadersPath: "include",
            cSettings: [
                .define("fseeko", to: "fseek", .when(platforms: [.windows, .android])),    
                .define("ftello", to: "ftell", .when(platforms: [.windows, .android])),
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_CRT_NONSTDC_NO_WARNINGS", .when(platforms: [.windows])),
                .headerSearchPath("include"),
                .unsafeFlags([
                    "-Wno-enum-conversion",
                    "-Wno-tautological-constant-out-of-range-compare",
                    "-Wno-sizeof-pointer-memaccess",
                ])
            ]),
        .target(
            name: "lz4",
            path: "Sources/lz4",
            sources: [
                "lib/lz4.c",
                "lib/lz4frame.c",
                "lib/lz4hc.c",
                "lib/xxhash.c"],
            publicHeadersPath: "include"),
        .target(
            name: "lzma",
            path: "Sources/lzma",
            exclude: [],
            sources: [
                "C/7zAlloc.h",
                "C/7zArcIn.c",
                "C/7zBuf.c",
                "C/7zBuf2.c",
                "C/7zCrc.c",
                "C/7zCrcOpt.c",
                "C/7zDec.c",
                "C/7zFile.c",
                "C/7zStream.c",
                "C/Aes.c",
                "C/AesOpt.c",
                "C/Alloc.c",
                "C/Bcj2.c",
                "C/Bcj2Enc.c",
                "C/Bra.c",
                "C/Bra86.c",
                "C/BraIA64.c",
                "C/CpuArch.c",
                "C/Delta.c",
                "C/LzFind.c",
                "C/Lzma2Dec.c",
                "C/Lzma2DecMt.c",
                "C/Lzma2Enc.c",
                "C/Lzma86Dec.c",
                "C/Lzma86Enc.c",
                "C/LzmaDec.c",
                "C/LzmaEnc.c",
                "C/LzmaLib.c",
                "C/Ppmd7.c",
                "C/Ppmd7Dec.c",
                "C/Ppmd7Enc.c",
                "C/Sha256.c",
                "C/Sort.c",
                "C/Xz.c",
                "C/XzCrc64.c",
                "C/XzCrc64Opt.c",
                "C/XzDec.c",
                "C/XzEnc.c",
                "C/XzIn.c"
                ],
            publicHeadersPath: "C",
            cSettings: [
                .define("_7ZIP_ST"),
                //.unsafeFlags(["-march=native"]),
            ]),
        .target(
            name: "zlib",
            path: "Sources/zlib",
            sources: [
                "src/adler32.c",
                "src/compress.c",
                "src/crc32.c",
                "src/deflate.c",
                "src/gzclose.c",
                "src/gzlib.c",
                "src/gzread.c",
                "src/gzwrite.c",
                "src/infback.c",
                "src/inffast.c",
                "src/inflate.c",
                "src/inftrees.c",
                "src/trees.c",
                "src/uncompr.c",
                "src/zutil.c"],
            publicHeadersPath: "include",
            cSettings: [
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_CRT_NONSTDC_NO_WARNINGS", .when(platforms: [.windows])),
                .unsafeFlags([
                    "-Wno-shift-negative-value",
                ])
            ]),
        .target(
            name: "zstd",
            path: "Sources/zstd",
            exclude: ["lib/common/xxhash.c"], // duplicated, use lz4 instead
            sources: [
                "lib/common",
                "lib/compress",
                "lib/decompress",
                "lib/dictBuilder",
            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("lib"),
                .headerSearchPath("lib/common"),
                .headerSearchPath("lib/dictBuilder")]
        ),
    ],
    cLanguageStandard: .c11,
    cxxLanguageStandard: .cxx20
)
